# Generated by Django 5.0 on 2024-02-28 14:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='registermodel',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registermodel', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='registermodel',
            name='email',
            field=models.EmailField(max_length=400, unique=True),
        ),
        migrations.AlterField(
            model_name='registermodel',
            name='userid',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(default='No description')),
                ('ingredients', models.TextField()),
                ('steps', models.TextField(default='No steps')),
                ('image', models.ImageField(default=None, upload_to='images/')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='recipe.registermodel')),
            ],
        ),
    ]
